
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]  
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:

  dbt_demo:

    # This configures models found in models/raw/
    raw: # tables with raw data
      schema: raw
      transient: false
      materialized: table
      tags: raw

    # This configures models found in models/stg/  
    stg: # tables with data already prepared
      schema: stg
      materialized: view
      tags: stg

    # This configures models found in models/edw/  
    edw: # dimensions and facts tables
      materialized: incremental
      on_schema_change: append_new_columns
      transient: false
      tags: edw

    # This configures models found in models/views/
    views: # views consuming from edw objects
      schema: edw
      materialized: view
      transient: false
      tags: 
        - edw
        - view


# Configuring seeds
seeds:
  dbt_demo:
    +schema: raw
  

# Configuring snapshots    
snapshots:
  dbt_demo:
    target_schema: edw
    transient: false
