
version: 2

models:
  - name: stg_supermarket_sales
    description: "A starter dbt model"
    columns:
      - name: sales_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
