my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: lgpfcsl-gl07180

      # User/password auth
      user: hisingh
      password: Srinet@1234
      authenticator: username_password_mfa

      role: PC_DBT_ROLE
      database: PC_DBT_DB
      warehouse: PC_DBT_WH
      schema: DBT_VISA
      threads: 4
      client_session_keep_alive: False
      query_tag: visa_poc
